### ISSUE TITLE
velero-upgrade-crds job fails and then holds up deployment with bad kubectl image

### ISSUE THREAD

**Issue by tonylioon** [vmware-tanzu/helm-charts#303] opened 2021-09-14 17:26 UTC
**What steps did you take and what happened:**
I was installing some new schedules to my velero deployment and the velero-upgrade-crds (post-upgrade hooks) fails with this error:

```
Failed to apply default image tag "docker.io/bitnami/kubectl:1.19+": couldn't parse image reference "docker.io/bitnami/kubectl:1.19+": invalid reference format: InvalidImageName
```

![image](https://user-images.githubusercontent.com/52207276/133301324-e85fb123-84ed-4078-a206-b5fd354fa863.png)

the velero deployment itself succeeds but the post-upgrade hook for upgrading the crds hangs:

![image](https://user-images.githubusercontent.com/52207276/133306122-0ca47ad5-88a8-46f1-8e9f-046eddbb189b.png)

**What did you expect to happen:**
I expected the deployment to come up and the hook job to not hang.

**The output of the following commands will help us better understand what's going on**:

From my zsh:
```
Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition
```

...nothing really relevant in the deployment logs

**Anything else you would like to add:**
Might be an issue with the bitnami/kubectl tags for the 1.19+ version updated 6 hours ago

**Environment:**

- Velero version (use `velero version`):  v1.6.3
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:58Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.12-gke.2101", GitCommit:"c8d75ae17b4628860e58bcdbe73c1f29dae62361", GitTreeState:"clean", BuildDate:"2021-08-18T18:42:22Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): macOS Big Sure 11.5.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by tonylioon** [comment] 2021-09-14 18:31
Did some more digging and when I do `kubectl verision` I get this:
```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-gke.901", GitCommit:"db8463aecdfe0eb5d9067effa2fd5ab3ff7a988e", GitTreeState:"clean", BuildDate:"2021-08-04T23:27:42Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
And I think it is the switch done here: https://github.com/vmware-tanzu/helm-charts/pull/301, merged and published this morning, is causing invalid syntax for our docker images. 

Not sure what to do about this besides going back to 3.23.7 since `.Capabilities.KubeVersion.Minor` as 18+ is a system config but not a valid docker image config.

**Comment by jenting** [comment] 2021-09-15 08:29
This issue had been addressed in `2.23.8`. please check.

**Comment by sarahhodne** [comment] 2021-09-17 15:24
This ticket is different from #302, and is caused by #301 (the fix that was included in 2.23.8).

Using the 2.23.7 chart, it tries to pull `docker.io/bitnami/kubectl:1.20.7-eks-d88609`, but in 2.23.8, it tries to pull `docker.io/bitnami/kubectl:1.20+`.

This is my `kubectl version`:

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sarahhodne** [comment] 2021-09-22 12:36
A workaround was to specify the kubectl tag manually, since I deploy Velero with Terraform I could get the current version using a data source and do this:

```hcl
set {
  name  = "kubectl.image.tag"
  value = data.aws_eks_cluster.cluster.version
}
```

**Comment by jenting** [comment] 2021-09-23 07:53
Probably we need to run a regex filter on the major and minor versions.

Don't know why the cluster min version includes `+`. Does it fulfill the semver definition? :thinking:

**Closed** 2021-09-28 00:58 UTC
Labels: bug, velero
