### ISSUE TITLE
Fail to install velero helm chart 3.2.0. Getting error - job failed: BackoffLimitExceeded

### ISSUE THREAD

**Issue by basaveswar-kureti** [vmware-tanzu/helm-charts#550] opened 2024-02-20 19:03 UTC
**What steps did you take and what happened:**
This has been working until Feb 19th, 2024.

kubectl create ns velero-320
helm upgrade --debug --install velero vmware-tanzu/velero --version 3.2.0 --namespace velero-320

**What did you expect to happen:**
We have pinned to version 3.2.0 to avoid breakages and it has been working until yesterday.

**The output of the following commands will help us better understand what's going on**:
```
helm upgrade --debug --install velero vmware-tanzu/velero --version 3.2.0 --namespace velero-320
history.go:56: [debug] getting history for release velero
Release "velero" does not exist. Installing it now.
install.go:200: [debug] Original chart version: "3.2.0"
install.go:217: [debug] CHART PATH: /Users/kureti/Library/Caches/helm/repository/velero-3.2.0.tgz

client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD backuprepositories.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD backups.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD backupstoragelocations.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD deletebackuprequests.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD downloadrequests.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD podvolumebackups.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD podvolumerestores.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD restores.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD schedules.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD serverstatusrequests.velero.io is already present. Skipping.
client.go:134: [debug] creating 1 resource(s)
install.go:160: [debug] CRD volumesnapshotlocations.velero.io is already present. Skipping.
client.go:478: [debug] Starting delete for "velero-upgrade-crds" ClusterRole
client.go:482: [debug] Ignoring delete failure for "velero-upgrade-crds" rbac.authorization.k8s.io/v1, Kind=ClusterRole: clusterroles.rbac.authorization.k8s.io "velero-upgrade-crds" not found
client.go:134: [debug] creating 1 resource(s)
client.go:478: [debug] Starting delete for "velero-server-upgrade-crds" ServiceAccount
client.go:482: [debug] Ignoring delete failure for "velero-server-upgrade-crds" /v1, Kind=ServiceAccount: serviceaccounts "velero-server-upgrade-crds" not found
client.go:134: [debug] creating 1 resource(s)
client.go:478: [debug] Starting delete for "velero-upgrade-crds" ClusterRoleBinding
client.go:482: [debug] Ignoring delete failure for "velero-upgrade-crds" rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding: clusterrolebindings.rbac.authorization.k8s.io "velero-upgrade-crds" not found
client.go:134: [debug] creating 1 resource(s)
client.go:478: [debug] Starting delete for "velero-upgrade-crds" Job
client.go:482: [debug] Ignoring delete failure for "velero-upgrade-crds" batch/v1, Kind=Job: jobs.batch "velero-upgrade-crds" not found
client.go:134: [debug] creating 1 resource(s)
client.go:706: [debug] Watching for changes to Job velero-upgrade-crds with timeout of 5m0s
client.go:734: [debug] Add/Modify event for velero-upgrade-crds: ADDED
client.go:773: [debug] velero-upgrade-crds: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:734: [debug] Add/Modify event for velero-upgrade-crds: MODIFIED
client.go:773: [debug] velero-upgrade-crds: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:734: [debug] Add/Modify event for velero-upgrade-crds: MODIFIED
Error: failed pre-install: 1 error occurred:
	* job failed: BackoffLimitExceeded


helm.go:84: [debug] failed pre-install: 1 error occurred:
	* job failed: BackoffLimitExceeded

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`):  version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):Mac or Linux

**Comment by jenting** [comment] 2024-02-20 23:40
> This has been working until Feb 19th, 2024.

We did not touch the release recently. Perhaps the problem is the kubectl image isn't available.

**Comment by basaveswar-kureti** [comment] 2024-02-21 14:14
@jenting Thanks for your response. Were you able to reproduce this issue using above mentioned commands ?

>  Perhaps the problem is the kubectl image isn't available.

Could you elaborate more on this ? Is there any workaround to specify the kubectl image through configuration ?

**Comment by basaveswar-kureti** [comment] 2024-02-21 21:06
Looks like this issue is coming specifically with velero image versions v1.11.0 & v1.12.0
This copied /tmp/sh from kubectl image seems to be incompatible with velero transitive dependencies in docker image versions 11 & 12
https://github.com/vmware-tanzu/helm-charts/blob/velero-3.2.0/charts/velero/templates/upgrade-crds/upgrade-crds.yaml#L74

It is giving the following error.
```
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/sh)
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/sh)
```

**Comment by mpkuth** [comment] 2024-02-22 01:18
We're also running into this issue and it started at about the same time. We believe that it is due to changes in the `bitnami/kubectl` image, but are still working to confirm that. Here's what we've found so far.

We have one cluster that is working and can see
```
  - names:
    - docker.io/bitnami/kubectl@sha256:0a3599824bccdd94ce461052e9fe9bea92ef9e84f7fb8ab75c98aeccd766cb03
    - docker.io/bitnami/kubectl:1.26
    sizeBytes: 80374891
```

And many others failing consistently with
```
    - docker.io/bitnami/kubectl@sha256:40a1d870fa3289fdffc4b7e86bc9434bd4ab02686bccbf4b800827b3744e04d1
    - docker.io/bitnami/kubectl:1.26
    sizeBytes: 87080325
```

Overriding the [kubectl image digest](https://github.com/vmware-tanzu/helm-charts/blob/1e6a5b46a59d2dae8153fa8c0794bad84e1d63e1/charts/velero/values.yaml#L270) in the failing clusters to match the digest in the working cluster cause them to start working.

---

We found https://github.com/bitnami/containers/issues/53360 with a comment from yesterday

> Debian 12 containers are already being released, for instance,
> ...
> The whole catalog should be released during the next hours/days.

https://packages.debian.org/source/bullseye/glibc
vs
https://packages.debian.org/source/bookworm/glibc

The timing does seem to line up as the [last 1.26-debian-11 image](https://hub.docker.com/layers/bitnami/kubectl/1.26-debian-11/images/sha256-d78cec446[…]b243e1e5e1127e1c90f0988394830073fa3d143d3d7ea?context=explore
) was pushed five days ago (last Friday) and we started seeing this problem on Monday.

That issue points to https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/. So the default tag used by the chart is a rolling tag, not an immutable one.

https://github.com/vmware-tanzu/helm-charts/blob/b4ced58cda7165a1217c6bdff14539bc540a83a0/charts/velero/templates/upgrade-crds/upgrade-crds.yaml#L49

Which would explain what we're seeing in our clusters since we don't explicitly set that chart value.

---

We're using [velero chart version 5.1.0](https://github.com/vmware-tanzu/helm-charts/blob/velero-5.1.0/charts/velero/values.yaml) with default values for [image](https://github.com/vmware-tanzu/helm-charts/blob/1e6a5b46a59d2dae8153fa8c0794bad84e1d63e1/charts/velero/values.yaml#L32-L43) and [kubectl](https://github.com/vmware-tanzu/helm-charts/blob/1e6a5b46a59d2dae8153fa8c0794bad84e1d63e1/charts/velero/values.yaml#L265-L281).

**Comment by jenting** [comment] 2024-05-16 12:13
Related issue #559, closing it.

**Closed by jenting** 2024-05-16 12:13 UTC
Labels: bug, velero, upgrade

**Comment by jfouche-vendavo** [comment] 2025-03-14 18:57
Getting this issue today - 14 Mar 2025

**Comment by virasana** [comment] 2025-03-14 18:57
Getting this issue today 14 Mar 2025
