### ISSUE TITLE
helm upgrade for velero failing error Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred: 	* job failed: BackoffLimitExceeded

### ISSUE THREAD

**Issue by sachinmane1983** [vmware-tanzu/helm-charts#552] opened 2024-02-22 17:47 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
helm upgrade for velero failing

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

helm.sh/chart: velero-2.31.5
image: velero/velero:v1.9.1
image: velero/velero-plugin-for-gcp:v1.5.0

error
Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred:
	* job failed: BackoffLimitExceeded

Error: Process completed with exit code 1.
POD log showing below error msgs
"/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/sh)"

**Comment by exactlyaron** [comment] 2024-02-26 09:37
@sachinmane1983 this is a duplicate of https://github.com/vmware-tanzu/helm-charts/issues/550

**Closed** 2024-05-16 12:13 UTC
Labels: bug, velero, upgrade
